### ISSUE TITLE
How can I add a job for it ? Please

### ISSUE THREAD

**Issue by YacineAyechi** [OsmiumOP/osm-burgers#1]

**Comment by OsmiumOP** [comment]
@YacineAyechi There is a seperate branch in the same repository named `separatejob`

**Comment by YacineAyechi** [comment]
oh okay thanks

**Comment by YacineAyechi** [comment]
oh, there's a problem in job_client.lua 
![image](https://user-images.githubusercontent.com/70200937/125450142-76b1b75d-aed9-4ed2-9d51-3a519c27f044.png)
